#!/bin/sh

for program in "$@"
do
	# echo "the value of program is $program"
	path="/usr/bin/"
	# echo "the value of path is $path"
	prog=$path$program
	# echo "the value of prog is $prog"
	if [[ -x $prog ]]; then
		echo "launching $program..."
		$prog &> /dev/null &
		disown
	else
		echo "the program \"$program\" does not exist in your path."
	fi
done
