#!/bin/bash
#
#  Masalla Icon Theme
#
#  Copyright 2021 hayder majid <hayder@riseup.net>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, you can download it from here:
#  https://www.gnu.org/licenses/gpl-3.0.html
#
# clean script for masalla icon themes 
# Written by Written by Hayder Majid(Hayder Ctee) <hayder@riseup.net>

if [ -d /usr/share/icons/masalla ]; then 
    rm -Rf /usr/share/icons/masalla
    rm -Rf /usr/share/icons/masalla-dark
fi
if [ -d $HOME/.icons/masalla ]; then
    rm -Rf $HOME/.icons/masalla
    rm -Rf $HOME/.icons/masalla-dark
fi
