#!/bin/bash
#
#  Masalla Icon Theme
#
#  Copyright 2021 hayder majid <hayder@riseup.net>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, you can download it from here:
#  https://www.gnu.org/licenses/gpl-3.0.html
#
# uninstalling script for masalla icon themes 
echo "We're sorry for removing Masalla Icon Theme from your system :-(" 
ROOT_UID=0
if [ "$UID" -ne "$ROOT_UID" ]
then
	echo "masalla icon themes was installed in $HOME/.icons and will be removed. According to your choices during installation, some default icons will be restored."
else
	echo "masalla icon themes was installed in /usr/share/icons and will be removed. According to your choices during installation, some default icons will be restored."
fi
echo ""
read -p "Do you want to continue ? [Y]es, [N]o : " response
case $response in
	[Yy]* ) ;;
    [Nn]* ) exit 99;;
    * ) echo "Wrong value: uninstall aborted."; exit 1;;
esac
if [ "$UID" -eq "$ROOT_UID" ]
then
	sudo ./CLEAN
else
	sudo ./CLEAN
fi
echo ""
echo "To find the latest update, please check the main repository :"
echo " https://notabug.org/masalla-art/masalla-icon-theme"
echo "Uninstall complete. Bey :-("
exit 0
